spring:
  profiles:
    active: development

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/agency
    username: postgres
    password: 1

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false

    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

logging:
  #  file: logs/application-debug.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: ERROR
    com.agency: DEBUG
    org.hibernate: ERROR

server:
  port: 80

app:
  jwtSecret: somesecretkey
  jwtExpirationInMs: 604800000